name: Update Virtual Machine

on:
  push:
    branches: [ main ]
    paths:
      - 'vm-update/**'

jobs:
  update-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Update VM
        run: |
          echo "THere is a change in vm-update/ folder"
          echo "To update VM do: vagrant reload --provision"